### ISSUE TITLE
kinematics problems dt

### ISSUE THREAD

**Issue by kassasin** [Rhoban/placo#5]
I found some problems in kinematics_solver.cpp:
https://github.com/Rhoban/placo/blob/4d8119a623ad73e4f3536b11cd72f706054810f5/src/placo/kinematics/kinematics_solver.cpp#L374
When dt is not zero,robot.state.q should be integrate with dt?
But if I integrate robot.state.q with dt,robot tracking end effector is very slow . I try to modify position task's weight or orientation task's weight,I found no effect .

**Comment by Gregwar** [comment]
Maybe we can rename some variables to make it more explicit what is q dot and delta q indeed

If both the target position and orientation can be reached, the weight will have no effect, the weights only affect the trade-off happening when one task is not entirely feasible, maybe this is why you don't see the difference in your case?

**Comment by kassasin** [comment]
I can't find the relevant code to use these weights, can you point me to it?

**Comment by Gregwar** [comment]
The task weights are the arguments of relevant `task.configure` method

`configure` first argument is the task name, second argument is either `soft` or `hard` and the third argument is it's weight

For frame tasks, which actually are wrapper for position+orientation tasks, you can pass two different weight (this is equivalent to configuring separately the position and orientation)

**Comment by kassasin** [comment]
@Gregwar Thanks,I just get more deep into code .These parameters finally through this line:
https://github.com/Rhoban/placo/blob/4d8119a623ad73e4f3536b11cd72f706054810f5/src/placo/kinematics/kinematics_solver.cpp#L338
and the problem will use slack variables to make effect .Am I right?

**Comment by Gregwar** [comment]
Slack variables are only needed for soft inequalities
For equalities, the soft equality will be turned into an objective function

See https://placo.readthedocs.io/en/latest/kinematics/concepts.html

**Comment by kassasin** [comment]
Thank you very much, I understand totally .
